force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/ProjectLine_Resource__c.field-meta.xml
<CustomField>
    <fullName>ProjectLine_Resource__c</fullName>
    <label>ProjectLine-Resource</label>
    <referenceTo>ProjectLine_Resource__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectLine_Resource__c/ProjectLine_Resource__c.object-meta.xml
<CustomObject>
    <label>ProjectLine-Resource</label>
    <nameField>
        <displayFormat>PLR-{0000}</displayFormat>
        <label>ProjectLine-Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectLine-Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <displayFormat>PLT-{0000}</displayFormat>
        <label>Project Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Product</relationshipLabel>
    <relationshipName>Project_Product</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectDataServiceTest.cls
@isTest
private class ProjectDataServiceTest {
  @isTest
  static void testGetProjectLineItemWithProjectId() {
    String projectId;
    List<ProjectLineItem__c> projectLineItemsToTest = ProjectDataService.getProjectLineItem(
      projectId
    );
    List<ProjectLineItem__c> projectLineItemsWithIdExpected = [
      SELECT Id
      FROM ProjectLineItem__c
      WHERE Project__r.Id = :projectId
    ];
    System.assertEquals(
      projectLineItemsToTest.size(),
      projectLineItemsWithIdExpected.size(),
      'The projectLineItems query did not return the right about of projectLineItems'
    );
  }

  @isTest
  static void testGetResourcePerRole() {
    String resourceRole;
    List<User> resourcesPerRolToTest = ProjectDataService.getAllResourcePerRole(
      resourceRole
    );
    List<User> resourcesPerRolWithIdExpected = [
      SELECT Id
      FROM User
      WHERE UserRole.Name = :resourceRole
    ];
    System.assertEquals(
      resourcesPerRolToTest.size(),
      resourcesPerRolWithIdExpected.size(),
      'The Resources query did not return the right about of Resource'
    );
  }
  @isTest
  static void testUpsertProjectLineResource() {
    List<ProjectLine_Resource__c> data;
    ProjectDataService.upsertProjectLineResource(data);
  }

  @isTest
  static void testGetProjectTaskPorResource() {
    List<ProjectLine_Resource__c> ProjectLineResourceTasksToTest = ProjectDataService.getProjectTaskPorResource();
    List<ProjectLine_Resource__c> ProjectLineResourceTasksExpected = [
      SELECT Id
      FROM ProjectLine_Resource__c
    ];
    System.assertEquals(
      ProjectLineResourceTasksExpected.size(),
      ProjectLineResourceTasksToTest.size(),
      'The Project Tasks query did not return the right about of Project Tasks'
    );
  }

  @isTest
  static void testUpdateProjectTasks() {
    List<Project_Task__c> data;
    ProjectDataService.updateProjectTasks(data);
  }
}