force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectsSquad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Hours__c</fullName>
    <label>Estimated Hours</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/ProjectLine_Resource__c.field-meta.xml
<CustomField>
    <fullName>ProjectLine_Resource__c</fullName>
    <label>ProjectLine-Resource</label>
    <referenceTo>ProjectLine_Resource__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Worked_Hours__c.field-meta.xml
<CustomField>
    <fullName>Worked_Hours__c</fullName>
    <label>Worked Hours</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLine_Resource__c/ProjectLine_Resource__c.object-meta.xml
<CustomObject>
    <label>ProjectLine-Resource</label>
    <nameField>
        <displayFormat>PLR-{0000}</displayFormat>
        <label>ProjectLine-Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectLine-Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLine_Resource__c/fields/Project_Product__c.field-meta.xml
<CustomField>
    <fullName>Project_Product__c</fullName>
    <label>Project Product</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>ProjectLine-Resources</relationshipLabel>
    <relationshipName>ProjectLine_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectLine_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectLine_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectLine_Resource__c/fields/Squad_Leader__c.field-meta.xml
<CustomField>
    <fullName>Squad_Leader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Squad Leader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <displayFormat>PLT-{0000}</displayFormat>
        <label>Project Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Product</relationshipLabel>
    <relationshipName>Project_Product</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Quantity_hours__c.field-meta.xml
<CustomField>
    <fullName>Quantity_hours__c</fullName>
    <label>Quantity-hours</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Product Manager</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Consultor</fullName>
                <isActive>false</isActive>
                <label>Consultor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectDataService.cls
public with sharing class ProjectDataService {


  @AuraEnabled(Cacheable=true)
  public static List<ProjectLineItem__c> getProjectLineItem(String projectId) {
    List<ProjectLineItem__c> query = new List<ProjectLineItem__c>();

    query = [SELECT Project__r.Id, Project__r.Name, Role__c, Quantity_hours__c, Project__r.Start_Date__c, Project__r.End_Date__c, Project__r.Squad_Lead__c ,
    (SELECT Resource__r.Name, Resource__r.UserRole.Name, Resource__r.RatePerHour__c, Allocated_Hours__c,Estimated_Cost__c, Start_Date__c, End_Date__c, Squad_Leader__c 
    FROM ProjectLine_Resources__r) 
    FROM ProjectLineItem__c
    WHERE Project__r.Id = :projectId];
    return query;
    // allresourceList = [SELECT Name,username,UserRole.Name,RatePerHour__c  FROM User where UserRole.Name=:resourceRole];
  }
  @AuraEnabled(Cacheable=true)
  public static List<User> getAllResourcePerRole(String resourceRole) {
    List<User> allresourceList = new List<User>();

    allresourceList = [
      SELECT
        Name,
        RatePerHour__c,
        (
          SELECT
            Project_Product__r.Project__r.End_Date__c,
            Project_Product__r.Project__r.Start_Date__c
          FROM ProjectLine_Resources__r
        )
      FROM User
      WHERE UserRole.Name = :resourceRole
    ];
    return allresourceList;

    // allresourceList = [SELECT Name,username,UserRole.Name,RatePerHour__c  FROM User where UserRole.Name=:resourceRole];
  }

  @AuraEnabled
  public static void upsertProjectLineResource(List<ProjectLine_Resource__c> data) {
    System.debug(data);
    upsert data;
  }


  @AuraEnabled(Cacheable=true)
  public static List<ProjectLine_Resource__c> getProjectTaskPorResource() {
    List<ProjectLine_Resource__c> query = new List<ProjectLine_Resource__c>();

    
    query = [SELECT Name, Project_Product__r.Project__r.Id,Project_Product__r.Project__r.Name, (SELECT Name,Stage__c, Estimated_Hours__c,Start_Date__c, End_Date__c,Worked_Hours__c ,ProjectLine_Resource__r.Name FROM Project_Tasks__r WHERE Stage__c != 'Completed' ORDER BY Stage__c ,Start_Date__c ) FROM ProjectLine_Resource__c  WHERE Resource__c = :UserInfo.getUserId()  ];
    return query;
 
  }

  
  @AuraEnabled
  public static void updateProjectTasks(List<Project_Task__c> data) {
    System.debug(data);
    update data;
  }

 
}